name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: configure git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: build heob32.exe
        run: make BITS=32 PREF= heob32.exe
        env:
          PATH: c:\mingw32\bin;c:\msys64\usr\bin
      - name: build heob64.exe
        run: make BITS=64 PREF= heob64.exe
        env:
          PATH: c:\mingw64\bin;c:\msys64\usr\bin

      - name: compress debug artifact
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run: 7z a -mx=9 heob-$GITHUB_REF_NAME-dbg.7z heob32.exe heob64.exe

      - name: upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: heob-debug
          if-no-files-found: error
          path: |
            heob32.exe
            heob64.exe

      - name: strip heob32.exe
        run: make BITS=32 PREF= strip-heob32
        env:
          PATH: c:\mingw32\bin;c:\msys64\usr\bin
      - name: strip heob64.exe
        run: make BITS=64 PREF= strip-heob64
        env:
          PATH: c:\mingw64\bin;c:\msys64\usr\bin

      - name: upload unsigned artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          name: heob-unsigned
          if-no-files-found: error
          path: |
            heob32.exe
            heob64.exe
      - name: sign
        uses: signpath/github-action-submit-signing-request@v1
        env:
          SIGNPATH_SIGNING_POLICY_SLUG: ${{ (startsWith(github.ref, 'refs/tags/')) && 'release-signing' || 'test-signing' }}
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ vars.SIGNPATH_ORGANIZATION_ID }}'
          project-slug: 'heob'
          signing-policy-slug: '${{ env.SIGNPATH_SIGNING_POLICY_SLUG }}'
          github-artifact-id: "${{ steps.upload-unsigned-artifact.outputs.artifact-id }}"
          wait-for-completion: true
          output-artifact-directory: '.'

      - name: upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: heob
          if-no-files-found: error
          path: |
            heob32.exe
            heob64.exe

      - name: build allocer32.exe
        run: make BITS=32 PREF= allocer32.exe
        env:
          PATH: c:\mingw32\bin;c:\msys64\usr\bin
      - name: build allocer64.exe
        run: make BITS=64 PREF= allocer64.exe
        env:
          PATH: c:\mingw64\bin;c:\msys64\usr\bin
      - name: install test dependencies
        run: c:\msys64\usr\bin\bash.exe -l -c "pacman -S --noconfirm make diffutils"
      - name: test
        shell: bash
        run: |
          make IGNORED_TESTS="68" tests
          head -n-0 test*.diff || true
        env:
          PATH: c:\msys64\usr\bin
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          if-no-files-found: error
          path: |
            allocer*.exe
            dll-alloc*.dll
            test*.diff
      - name: check for test failure
        shell: cmd
        run: |
          if exist test*.diff exit 1

      - name: compress release artifact
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run: 7z a -mx=9 heob-$GITHUB_REF_NAME.7z heob32.exe heob64.exe

      - name: release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: heob ${{ github.ref_name }}
          files: |
            heob-${{ github.ref_name }}.7z
            heob-${{ github.ref_name }}-dbg.7z
